name: Testes do Projeto

on:
  push:
    branches:
      - main
      - cadastramento
      - validacaoLogin
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configurar o Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dar permissão de execução ao Gradle Wrapper
        run: chmod +x gradlew

      - name: Verificar a versão do Gradle
        run: ./gradlew --version

      - name: Testar configuração do Gradle
        run: ./gradlew help

      - name: Executar os testes
        run: ./gradlew test
